ARG BASE
FROM mcr.microsoft.com/powershell:${BASE}

SHELL ["pwsh", "-Command"]

USER ContainerAdministrator

# Work around: https://stackoverflow.com/questions/58310649/error-install-package-authenticode-issuer-in-powershell-module
RUN Install-Module -Name Pode -Scope AllUsers -Force -SkipPublisherCheck

USER ContainerUser

COPY app.ps1 app.ps1

CMD ["pwsh", "-File", "app.ps1"]
