ARG BASE
FROM mcr.microsoft.com/powershell:${BASE}

SHELL ["pwsh", "-Command"]

USER ContainerAdministrator

RUN Install-Module -Name Polaris -Force  

USER ContainerUser

COPY app.ps1 app.ps1

CMD ["pwsh", "-File", "app.ps1"]
